library(Racmacs)
library(ggplot2)
options(RacOptimizer.num_cores = 10)
dir <- "./data/HI_data/individual_HI_tables/"
acmap_dir <- "./analysis/antigenic_comparison/antigenic_maps/complete_maps"
acmap_simple_dir <- "./analysis/antigenic_comparison/antigenic_maps/maps"
coords_dir <- "./analysis/antigenic_comparison/antigenic_maps/coords"
#load individual maps
map1 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map1.ace')))
save.acmap(map1, file.path(acmap_simple_dir, 'map1.ace'))
map2 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map2.ace')))
save.acmap(map2, file.path(acmap_simple_dir, 'map2.ace'))
map3 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map3.ace')))
save.acmap(map3, file.path(acmap_simple_dir, 'map3.ace'))
map4 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map4.ace')))
save.acmap(map4, file.path(acmap_simple_dir, 'map4.ace'))
map5 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map5.ace')))
save.acmap(map5, file.path(acmap_simple_dir, 'map5.ace'))
map6 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map6.ace')))
save.acmap(map6, file.path(acmap_simple_dir, 'map6.ace'))
map7 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map7.ace')))
save.acmap(map7, file.path(acmap_simple_dir, 'map7.ace'))
map8 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map8.ace')))
save.acmap(map8, file.path(acmap_simple_dir, 'map8.ace'))
map9 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map9.ace')))
save.acmap(map9, file.path(acmap_simple_dir, 'map9.ace'))
map10 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map10.ace')))
save.acmap(map10, file.path(acmap_simple_dir, 'map10.ace'))
map11 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map11.ace')))
save.acmap(map11, file.path(acmap_simple_dir, 'map11.ace'))
map12 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map12.ace')))
save.acmap(map12, file.path(acmap_simple_dir, 'map12.ace'))
map13 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map13.ace')))
save.acmap(map13, file.path(acmap_simple_dir, 'map13.ace'))
map14 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map14.ace')))
save.acmap(map14, file.path(acmap_simple_dir, 'map14.ace'))
map15 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map15.ace')))
save.acmap(map15, file.path(acmap_simple_dir, 'map15.ace'))
map16 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map16.ace')))
save.acmap(map16, file.path(acmap_simple_dir, 'map16.ace'))
map17 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map17.ace')))
save.acmap(map17, file.path(acmap_simple_dir, 'map17.ace'))
map18 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map18.ace')))
save.acmap(map18, file.path(acmap_simple_dir, 'map18.ace'))
map19 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map19.ace')))
save.acmap(map19, file.path(acmap_simple_dir, 'map19.ace'))
map20 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map20.ace')))
save.acmap(map20, file.path(acmap_simple_dir, 'map20.ace'))
map21 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map21.ace')))
save.acmap(map21, file.path(acmap_simple_dir, 'map21.ace'))
map22 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map22.ace')))
save.acmap(map22, file.path(acmap_simple_dir, 'map22.ace'))
map23 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map23.ace')))
save.acmap(map23, file.path(acmap_simple_dir, 'map23.ace'))
map24 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map24.ace')))
save.acmap(map24, file.path(acmap_simple_dir, 'map24.ace'))
map25 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map25.ace')))
save.acmap(map25, file.path(acmap_simple_dir, 'map25.ace'))
map26 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map26.ace')))
save.acmap(map26, file.path(acmap_simple_dir, 'map26.ace'))
map27 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map27.ace')))
save.acmap(map27, file.path(acmap_simple_dir, 'map27.ace'))
map28 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map28.ace')))
save.acmap(map28, file.path(acmap_simple_dir, 'map28.ace'))
map29 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map29.ace')))
save.acmap(map29, file.path(acmap_simple_dir, 'map29.ace'))
map30 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map30.ace')))
save.acmap(map30, file.path(acmap_simple_dir, 'map30.ace'))
map31 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map31.ace')))
save.acmap(map31, file.path(acmap_simple_dir, 'map31.ace'))
map32 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map32.ace')))
save.acmap(map32, file.path(acmap_simple_dir, 'map32.ace'))
map33 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map33.ace')))
save.acmap(map33, file.path(acmap_simple_dir, 'map33.ace'))
map34 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map34.ace')))
save.acmap(map34, file.path(acmap_simple_dir, 'map34.ace'))
map35 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map35.ace')))
save.acmap(map35, file.path(acmap_simple_dir, 'map35.ace'))
map36 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map36.ace')))
save.acmap(map36, file.path(acmap_simple_dir, 'map36.ace'))
map37 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map37.ace')))
save.acmap(map37, file.path(acmap_simple_dir, 'map37.ace'))
map38 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map38.ace')))
save.acmap(map38, file.path(acmap_simple_dir, 'map38.ace'))
map39 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map39.ace')))
save.acmap(map39, file.path(acmap_simple_dir, 'map39.ace'))
map40 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map40.ace')))
save.acmap(map40, file.path(acmap_simple_dir, 'map40.ace'))
map41 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map41.ace')))
save.acmap(map41, file.path(acmap_simple_dir, 'map41.ace'))
map42 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map42.ace')))
save.acmap(map42, file.path(acmap_simple_dir, 'map42.ace'))
map43 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map43.ace')))
save.acmap(map43, file.path(acmap_simple_dir, 'map43.ace'))
map44 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map44.ace')))
save.acmap(map44, file.path(acmap_simple_dir, 'map44.ace'))
map45 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map45.ace')))
save.acmap(map45, file.path(acmap_simple_dir, 'map45.ace'))
map46 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map46.ace')))
save.acmap(map46, file.path(acmap_simple_dir, 'map46.ace'))
map47 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map47.ace')))
save.acmap(map47, file.path(acmap_simple_dir, 'map47.ace'))
map48 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map48.ace')))
save.acmap(map48, file.path(acmap_simple_dir, 'map48.ace'))
map49 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map49.ace')))
save.acmap(map49, file.path(acmap_simple_dir, 'map49.ace'))
map50 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map50.ace')))
save.acmap(map50, file.path(acmap_simple_dir, 'map50.ace'))
map51 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map51.ace')))
save.acmap(map51, file.path(acmap_simple_dir, 'map51.ace'))
map52 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map52.ace')))
save.acmap(map52, file.path(acmap_simple_dir, 'map52.ace'))
map53 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map53.ace')))
save.acmap(map53, file.path(acmap_simple_dir, 'map53.ace'))
map54 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map54.ace')))
save.acmap(map54, file.path(acmap_simple_dir, 'map54.ace'))
map55 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map55.ace')))
save.acmap(map55, file.path(acmap_simple_dir, 'map55.ace'))
map56 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map56.ace')))
save.acmap(map56, file.path(acmap_simple_dir, 'map56.ace'))
map57 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map57.ace')))
save.acmap(map57, file.path(acmap_simple_dir, 'map57.ace'))
map58 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map58.ace')))
save.acmap(map58, file.path(acmap_simple_dir, 'map58.ace'))
map59 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map59.ace')))
save.acmap(map59, file.path(acmap_simple_dir, 'map59.ace'))
map60 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map60.ace')))
save.acmap(map60, file.path(acmap_simple_dir, 'map60.ace'))
map61 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map61.ace')))
save.acmap(map61, file.path(acmap_simple_dir, 'map61.ace'))
map62 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map62.ace')))
save.acmap(map62, file.path(acmap_simple_dir, 'map62.ace'))
map63 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map63.ace')))
save.acmap(map63, file.path(acmap_simple_dir, 'map63.ace'))
map64 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map64.ace')))
save.acmap(map64, file.path(acmap_simple_dir, 'map64.ace'))
map65 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map65.ace')))
save.acmap(map65, file.path(acmap_simple_dir, 'map65.ace'))
map66 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map66.ace')))
save.acmap(map66, file.path(acmap_simple_dir, 'map66.ace'))
map67 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map67.ace')))
save.acmap(map67, file.path(acmap_simple_dir, 'map67.ace'))
map68 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map68.ace')))
save.acmap(map68, file.path(acmap_simple_dir, 'map68.ace'))
map69 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map69.ace')))
save.acmap(map69, file.path(acmap_simple_dir, 'map69.ace'))
map70 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map70.ace')))
save.acmap(map70, file.path(acmap_simple_dir, 'map70.ace'))
map71 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map71.ace')))
save.acmap(map71, file.path(acmap_simple_dir, 'map71.ace'))
map72 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map72.ace')))
save.acmap(map72, file.path(acmap_simple_dir, 'map72.ace'))
map73 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map73.ace')))
save.acmap(map73, file.path(acmap_simple_dir, 'map73.ace'))
map74 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map74.ace')))
save.acmap(map74, file.path(acmap_simple_dir, 'map74.ace'))
map75 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map75.ace')))
save.acmap(map75, file.path(acmap_simple_dir, 'map75.ace'))
map76 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map76.ace')))
save.acmap(map76, file.path(acmap_simple_dir, 'map76.ace'))
map77 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map77.ace')))
save.acmap(map77, file.path(acmap_simple_dir, 'map77.ace'))
map78 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map78.ace')))
save.acmap(map78, file.path(acmap_simple_dir, 'map78.ace'))
map79 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map79.ace')))
save.acmap(map79, file.path(acmap_simple_dir, 'map79.ace'))
map80 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map80.ace')))
save.acmap(map80, file.path(acmap_simple_dir, 'map80.ace'))
map81 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map81.ace')))
save.acmap(map81, file.path(acmap_simple_dir, 'map81.ace'))
map82 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map82.ace')))
save.acmap(map82, file.path(acmap_simple_dir, 'map82.ace'))
map83 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map83.ace')))
save.acmap(map83, file.path(acmap_simple_dir, 'map83.ace'))
map84 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map84.ace')))
save.acmap(map84, file.path(acmap_simple_dir, 'map84.ace'))
map85 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map85.ace')))
save.acmap(map85, file.path(acmap_simple_dir, 'map85.ace'))
map86 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map86.ace')))
save.acmap(map86, file.path(acmap_simple_dir, 'map86.ace'))
map87 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map87.ace')))
save.acmap(map87, file.path(acmap_simple_dir, 'map87.ace'))
map88 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map88.ace')))
save.acmap(map88, file.path(acmap_simple_dir, 'map88.ace'))
map89 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map89.ace')))
save.acmap(map89, file.path(acmap_simple_dir, 'map89.ace'))
map90 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map90.ace')))
save.acmap(map90, file.path(acmap_simple_dir, 'map90.ace'))
map91 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map91.ace')))
save.acmap(map91, file.path(acmap_simple_dir, 'map91.ace'))
map92 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map92.ace')))
save.acmap(map92, file.path(acmap_simple_dir, 'map92.ace'))
map93 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map93.ace')))
save.acmap(map93, file.path(acmap_simple_dir, 'map93.ace'))
map94 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map94.ace')))
save.acmap(map94, file.path(acmap_simple_dir, 'map94.ace'))
map95 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map95.ace')))
save.acmap(map95, file.path(acmap_simple_dir, 'map95.ace'))
map96 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map96.ace')))
save.acmap(map96, file.path(acmap_simple_dir, 'map96.ace'))
map97 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map97.ace')))
save.acmap(map97, file.path(acmap_simple_dir, 'map97.ace'))
map98 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map98.ace')))
save.acmap(map98, file.path(acmap_simple_dir, 'map98.ace'))
map99 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map99.ace')))
save.acmap(map99, file.path(acmap_simple_dir, 'map99.ace'))
map100 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map100.ace')))
save.acmap(map100, file.path(acmap_simple_dir, 'map100.ace'))
map101 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map101.ace')))
save.acmap(map101, file.path(acmap_simple_dir, 'map101.ace'))
map102 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map102.ace')))
save.acmap(map102, file.path(acmap_simple_dir, 'map102.ace'))
map103 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map103.ace')))
save.acmap(map103, file.path(acmap_simple_dir, 'map103.ace'))
map104 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map104.ace')))
save.acmap(map104, file.path(acmap_simple_dir, 'map104.ace'))
map105 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map105.ace')))
save.acmap(map105, file.path(acmap_simple_dir, 'map105.ace'))
map106 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map106.ace')))
save.acmap(map106, file.path(acmap_simple_dir, 'map106.ace'))
map107 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map107.ace')))
save.acmap(map107, file.path(acmap_simple_dir, 'map107.ace'))
map108 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map108.ace')))
save.acmap(map108, file.path(acmap_simple_dir, 'map108.ace'))
map109 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map109.ace')))
save.acmap(map109, file.path(acmap_simple_dir, 'map109.ace'))
map110 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map110.ace')))
save.acmap(map110, file.path(acmap_simple_dir, 'map110.ace'))
map111 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map111.ace')))
save.acmap(map111, file.path(acmap_simple_dir, 'map111.ace'))
map112 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map112.ace')))
save.acmap(map112, file.path(acmap_simple_dir, 'map112.ace'))
map113 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map113.ace')))
save.acmap(map113, file.path(acmap_simple_dir, 'map113.ace'))
map114 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map114.ace')))
save.acmap(map114, file.path(acmap_simple_dir, 'map114.ace'))
map115 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map115.ace')))
save.acmap(map115, file.path(acmap_simple_dir, 'map115.ace'))
map116 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map116.ace')))
save.acmap(map116, file.path(acmap_simple_dir, 'map116.ace'))
map117 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map117.ace')))
save.acmap(map117, file.path(acmap_simple_dir, 'map117.ace'))
map118 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map118.ace')))
save.acmap(map118, file.path(acmap_simple_dir, 'map118.ace'))
map119 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map119.ace')))
save.acmap(map119, file.path(acmap_simple_dir, 'map119.ace'))
map120 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map120.ace')))
save.acmap(map120, file.path(acmap_simple_dir, 'map120.ace'))
map121 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map121.ace')))
save.acmap(map121, file.path(acmap_simple_dir, 'map121.ace'))
map122 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map122.ace')))
save.acmap(map122, file.path(acmap_simple_dir, 'map122.ace'))
map123 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map123.ace')))
save.acmap(map123, file.path(acmap_simple_dir, 'map123.ace'))
map124 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map124.ace')))
save.acmap(map124, file.path(acmap_simple_dir, 'map124.ace'))
map125 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map125.ace')))
save.acmap(map125, file.path(acmap_simple_dir, 'map125.ace'))
map126 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map126.ace')))
save.acmap(map126, file.path(acmap_simple_dir, 'map126.ace'))
map127 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map127.ace')))
save.acmap(map127, file.path(acmap_simple_dir, 'map127.ace'))
map128 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map128.ace')))
save.acmap(map128, file.path(acmap_simple_dir, 'map128.ace'))
map129 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map129.ace')))
save.acmap(map129, file.path(acmap_simple_dir, 'map129.ace'))
map130 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map130.ace')))
save.acmap(map130, file.path(acmap_simple_dir, 'map130.ace'))
map131 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map131.ace')))
save.acmap(map131, file.path(acmap_simple_dir, 'map131.ace'))
map132 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map132.ace')))
save.acmap(map132, file.path(acmap_simple_dir, 'map132.ace'))
map133 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map133.ace')))
save.acmap(map133, file.path(acmap_simple_dir, 'map133.ace'))
map134 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map134.ace')))
save.acmap(map134, file.path(acmap_simple_dir, 'map134.ace'))
map135 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map135.ace')))
save.acmap(map135, file.path(acmap_simple_dir, 'map135.ace'))
map136 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map136.ace')))
save.acmap(map136, file.path(acmap_simple_dir, 'map136.ace'))
map137 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map137.ace')))
save.acmap(map137, file.path(acmap_simple_dir, 'map137.ace'))
map138 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map138.ace')))
save.acmap(map138, file.path(acmap_simple_dir, 'map138.ace'))
map139 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map139.ace')))
save.acmap(map139, file.path(acmap_simple_dir, 'map139.ace'))
map140 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map140.ace')))
save.acmap(map140, file.path(acmap_simple_dir, 'map140.ace'))
map141 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map141.ace')))
save.acmap(map141, file.path(acmap_simple_dir, 'map141.ace'))
map142 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map142.ace')))
save.acmap(map142, file.path(acmap_simple_dir, 'map142.ace'))
map143 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map143.ace')))
save.acmap(map143, file.path(acmap_simple_dir, 'map143.ace'))
map144 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map144.ace')))
save.acmap(map144, file.path(acmap_simple_dir, 'map144.ace'))
map145 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map145.ace')))
save.acmap(map145, file.path(acmap_simple_dir, 'map145.ace'))
map146 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map146.ace')))
save.acmap(map146, file.path(acmap_simple_dir, 'map146.ace'))
map147 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map147.ace')))
save.acmap(map147, file.path(acmap_simple_dir, 'map147.ace'))
map148 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map148.ace')))
save.acmap(map148, file.path(acmap_simple_dir, 'map148.ace'))
map149 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map149.ace')))
save.acmap(map149, file.path(acmap_simple_dir, 'map149.ace'))
map150 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map150.ace')))
save.acmap(map150, file.path(acmap_simple_dir, 'map150.ace'))
map151 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map151.ace')))
save.acmap(map151, file.path(acmap_simple_dir, 'map151.ace'))
map152 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map152.ace')))
save.acmap(map152, file.path(acmap_simple_dir, 'map152.ace'))
map153 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map153.ace')))
save.acmap(map153, file.path(acmap_simple_dir, 'map153.ace'))
map154 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map154.ace')))
save.acmap(map154, file.path(acmap_simple_dir, 'map154.ace'))
map155 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map155.ace')))
save.acmap(map155, file.path(acmap_simple_dir, 'map155.ace'))
map156 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map156.ace')))
save.acmap(map156, file.path(acmap_simple_dir, 'map156.ace'))
map157 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map157.ace')))
save.acmap(map157, file.path(acmap_simple_dir, 'map157.ace'))
map158 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map158.ace')))
save.acmap(map158, file.path(acmap_simple_dir, 'map158.ace'))
map159 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map159.ace')))
save.acmap(map159, file.path(acmap_simple_dir, 'map159.ace'))
map160 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map160.ace')))
save.acmap(map160, file.path(acmap_simple_dir, 'map160.ace'))
map161 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map161.ace')))
save.acmap(map161, file.path(acmap_simple_dir, 'map161.ace'))
map162 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map162.ace')))
save.acmap(map162, file.path(acmap_simple_dir, 'map162.ace'))
map163 <- keepBestOptimization(read.acmap(file.path(acmap_dir, 'map163.ace')))
save.acmap(map163, file.path(acmap_simple_dir, 'map163.ace'))
